### ISSUE TITLE
Error with manually added large files

### ISSUE THREAD

**Issue by instantflorian** [WBCE/Download-Gallery-WBCE#5]
When uploading a large file via FTP to /media/download_gallery (what is necessary when the file size is larger than the upload limit an/or the PDF upload would exhaust the script execution time) and adding it to the DLG as a "Medienverzeichnis Datei", the download from the frontend fails with the message " Sorry, your download failed.".
Furthermore, the file size is shown with "0" (FE/BE).

**Comment by NorHei** [comment]
is it ok i take a look after doing the other issues ?

**Comment by instantflorian** [comment]
yes, of course. I thought this would be Bianka's part anyway.

**Comment by instantflorian** [comment]
Correction: its not a file size but file name issue, the error occurs when the file name contains capital letters

**Comment by webbird** [comment]
I'll take a look at it.

**Comment by webbird** [comment]
Sorry, but works for me on Windows.

![2016-06-07 10_49_40](https://cloud.githubusercontent.com/assets/147354/15851652/fe03a894-2c9d-11e6-90c8-3b30fd1f8026.png)

![2016-06-07 10_52_04](https://cloud.githubusercontent.com/assets/147354/15851666/07387746-2c9e-11e6-8caa-256de8ce3469.png)

I'll try with a PDF now.

**Comment by webbird** [comment]
Tried with PDF (suffix PDF and pdf), works perfectly in my environment.

**Comment by webbird** [comment]
I think the reason is that the filename is converted to "all lowercase" in the DB.

![2016-06-07 11_26_39](https://cloud.githubusercontent.com/assets/147354/15852787/ccf78b26-2ca2-11e6-9ea9-2a0e896f00be.png)

This works perfectly on Windows but not in case sensitive OSes. Will have to check why the conversion was done.

**Comment by webbird** [comment]
The code in question was derived from the old module.

```
$file_link = $existingfile;
$path_parts = pathinfo($file_link);
$fileext = strtolower($path_parts['extension']);
if  ($remotelink == '') {
    $filename = strtolower($path_parts['basename']);
    $size = filesize(WB_PATH.MEDIA_DIRECTORY.'/download_gallery/'.$filename);
}
```

The entries in the DB are the same - filename converted to lowercase. It _may_ be no error in that version because I use the filename column for the download in V3, while the old version may use the link column. Anyway, the lowercase conversion doesn't seem to make much sense for me. The filename should be left as-is.

**Comment by NorHei** [comment]
100% agreed the strtolower filename is the problem .

**Comment by webbird** [comment]
Dunno why this was done anyway...
