### ISSUE TITLE
Dateigröße auch bei Unterordner erkennen / Recognize the datasize in subfolders

### ISSUE THREAD

**Issue by joergwbce** [WBCE/Download-Gallery-WBCE#6]
Vielleicht wäre es möglich, das Modul so zu gestalten, dass die Dateigröße auch bei Unterordnern von "downloadgallery" erkannt wird. 
Auch die Auswahl von bereits auf dem Server liegenden Daten, dürfte/sollte die Verzeichnisstruktur so anzeigen wie im normalen Dateimanager (Explorer etc.) und nicht alle einzelnen Dateien, egal ob diese im Hauptordner oder in einem Unterordner liegen. Dies würde die Übersichtlichkeit und somit auch Auswahl bei vielen abgelegten Downloaddateien enorm erleichtern.

Maybe its possible that the modul recognize the datasize even the file is in a subfolder.
Also it would be nice, if you select a file which is already on the server, that you see the whole directory structure - that means the subfolders too - and not only every single file, independt off where the are located, in the mainfolder or in a subfolder. this would improve the handling of many files a lot.

**Comment by NorHei** [comment]
Right now i am Working on elFinder as Filemanager 
https://forum.wbce.org/viewtopic.php?id=1586

Selecting and uploading files whith elFinder may be a really nice addition to Download Gallery. 
Or mabe make a new DLGallery...  

But for now we take a look into the module it there is a simple way to solve this ;-)

**Comment by webbird** [comment]
Im Augenblick ist das "by design" ganz bewußt so gemacht. (Und war IMHO auch schon beim alten Modul so.) Die Verwaltung der Dateien soll das Modul erledigen, einschließlich der Kategorien = Gruppen. Letztlich braucht es nur etwas Disziplin beim Benennen der Download-Dateien, was letztlich auch eine Art Kundenservice ist, denn der Besucher hat ja vielleicht auch einen unaufgeräumten Download-Folder. ;)

Das Arbeiten mit Unterordnern wirft einige Fragen auf:

* Soll ein Unterordner automatisch einer Gruppe entsprechen? --> Problem: Es gibt keine verschachtelten Gruppen, das ist auch nicht geplant, man hätte also maximal 1 Ebene gewonnen
* Wenn nein: Ich würde es verwirrend finden, Dateien aus irgendwelchen Unterordnern irgendwelchen ganz anderen Gruppen zuzuordnen

Einen eigenen Dateimanager einzubauen halte ich für oversized. Den elFinder zu benutzen stelle ich mir schwierig vor, da das Modul als Hybridmodul auch unter BC1 und BC2 laufen soll.

**Comment by webbird** [comment]
Wenn ich es richtig verstehe, ist das Hinzufügen der Dateien möglich, nur die Größe wird nicht erkannt? Das sollte machbar sein.

**Comment by webbird** [comment]
Probier' mal die geänderte save_file.php.
https://github.com/WBCE/Download-Gallery-WBCE/commit/4e921b553f9e7c7e78c08fadd431bd2a6bc84f84

**Comment by webbird** [comment]
Any thoughts on this? 
Gibt es irgendwelche Rückmeldungen hierzu?

**Comment by joergwbce** [comment]
Hallo Bianka,

JA :-) Ich habe soeben erst wieder Zeit gefunden an dem Projekt weiterzuarbeiten. Jetzt ist es SPITZE! Es wird mir die Verzeichnisstruktur, die im Ordner “downloadgallery” ist, bei der Auswahl angezeigt und auch die Dateigröße übernommen.

Ich finde diese Verbesserung sollte unbedingt ins Standardmodul eingebaut werden!

Vielen Dank nochmal!

LG,

Jörg

**Comment by webbird** [comment]
Bitte schön. :)
https://github.com/WBCE/Download-Gallery-WBCE/releases/tag/3.1.4
